import { z } from "zod";
import { defineTemplate, type TemplateDef } from "./types.js";

/** Join lines with LF and terminate the file with exactly one newline. */
export function lines(...parts: (string | readonly string[])[]): string {
  const flat: string[] = [];
  for (const p of parts) {
    if (typeof p === "string") flat.push(p);
    else flat.push(...p);
  }
  return `${flat.join("\n").replace(/\s+$/, "")}\n`;
}

const Ident = z
  .string()
  .regex(/^[A-Za-z_$][A-Za-z0-9_$]*$/, "must be a JavaScript identifier")
  .max(64);

const HttpMethod = z.enum(["GET", "POST", "PUT", "DELETE"]);

/** `a/b` segments, no dots, no leading/trailing slash — becomes `app/api/<segment>/route.ts`. */
const Segment = z
  .string()
  .regex(/^[a-z0-9][a-z0-9-]*(\/(\[[a-z][a-zA-Z0-9]*\]|[a-z0-9][a-z0-9-]*))*$/, "invalid segment")
  .max(128);

const SORT_METHODS = (ms: readonly z.output<typeof HttpMethod>[]): string[] => {
  const order = ["GET", "POST", "PUT", "DELETE"];
  return [...new Set(ms)].sort((a, b) => order.indexOf(a) - order.indexOf(b));
};

const routeHandler = defineTemplate(
  "Next.js 16 App Router route handler (`app/api/<segment>/route.ts`) — one exported async function per method, `NextRequest` in, `Response.json` out; optional Zod body validation on the non-GET methods.",
  z
    .object({
      segment: Segment,
      methods: z.array(HttpMethod).min(1).max(4),
      zodSchemaName: Ident.optional(),
    })
    .strict(),
  ({ segment, methods, zodSchemaName }) => {
    const schema = zodSchemaName;
    const head = [
      'import type { NextRequest } from "next/server";',
      ...(schema === undefined ? [] : [`import { ${schema} } from "./schema";`]),
      "",
      `// ${segment} — generated by @codai/axiom-emitters-web (web@2.0.0).`,
      "",
    ];
    const body = SORT_METHODS(methods).map((m) => {
      if (m === "GET") {
        return lines([
          "export async function GET(request: NextRequest): Promise<Response> {",
          "  const { searchParams } = new URL(request.url);",
          "  return Response.json({ ok: true, query: Object.fromEntries(searchParams) });",
          "}",
        ]).trimEnd();
      }
      if (m === "DELETE") {
        return lines([
          "export async function DELETE(_request: NextRequest): Promise<Response> {",
          "  return new Response(null, { status: 204 });",
          "}",
        ]).trimEnd();
      }
      const validate =
        schema === undefined
          ? ["  const data = (await request.json()) as unknown;"]
          : [
              "  const parsed = " + schema + ".safeParse(await request.json());",
              "  if (!parsed.success) {",
              "    return Response.json({ error: parsed.error.issues }, { status: 400 });",
              "  }",
              "  const data = parsed.data;",
            ];
      return lines([
        `export async function ${m}(request: NextRequest): Promise<Response> {`,
        ...validate,
        `  return Response.json({ ok: true, data }, { status: ${m === "POST" ? 201 : 200} });`,
        "}",
      ]).trimEnd();
    });
    return lines(head, body.join("\n\n"));
  },
);

const ZOD_FIELD = {
  string: "z.string().min(1)",
  number: "z.coerce.number()",
  boolean: "z.coerce.boolean()",
  email: "z.email()",
} as const;

const serverAction = defineTemplate(
  'Next.js 16 Server Action ("use server") validating FormData with Zod v4 and returning a `useActionState`-compatible `{ ok, errors, values }` state.',
  z
    .object({
      name: Ident,
      fields: z
        .array(
          z.object({ name: Ident, zod: z.enum(["string", "number", "boolean", "email"]) }).strict(),
        )
        .min(1)
        .max(50),
    })
    .strict(),
  ({ name, fields }) => {
    const State = `${name.charAt(0).toUpperCase()}${name.slice(1)}State`;
    return lines([
      '"use server";',
      "",
      'import { z } from "zod";',
      "",
      `// ${name} — generated by @codai/axiom-emitters-web (web@2.0.0).`,
      "",
      `const ${name}Schema = z.object({`,
      ...fields.map((f) => `  ${f.name}: ${ZOD_FIELD[f.zod]},`),
      "});",
      "",
      `export interface ${State} {`,
      "  ok: boolean;",
      "  errors: Record<string, string[]>;",
      `  values: Partial<z.output<typeof ${name}Schema>>;`,
      "}",
      "",
      `export const initial${State}: ${State} = { ok: false, errors: {}, values: {} };`,
      "",
      `export async function ${name}(`,
      `  _prev: ${State},`,
      "  formData: FormData,",
      `): Promise<${State}> {`,
      `  const parsed = ${name}Schema.safeParse({`,
      ...fields.map((f) => `    ${f.name}: formData.get("${f.name}"),`),
      "  });",
      "  if (!parsed.success) {",
      "    const flat = z.flattenError(parsed.error);",
      "    return { ok: false, errors: flat.fieldErrors as Record<string, string[]>, values: {} };",
      "  }",
      "  return { ok: true, errors: {}, values: parsed.data };",
      "}",
    ]);
  },
);

const honoRoute = defineTemplate(
  'Hono 4 route module exporting a `Hono` instance with one handler per method; mount it with `app.route("/", <name>)`.',
  z
    .object({
      name: Ident,
      path: z
        .string()
        .regex(/^\/[A-Za-z0-9/:_-]*$/, "path must start with /")
        .max(128),
      methods: z.array(HttpMethod).min(1).max(4),
    })
    .strict(),
  ({ name, path, methods }) =>
    lines([
      'import { Hono } from "hono";',
      "",
      `// ${name} — generated by @codai/axiom-emitters-web (web@2.0.0).`,
      "",
      `export const ${name} = new Hono();`,
      "",
      ...SORT_METHODS(methods).flatMap((m) => [
        `${name}.${m.toLowerCase()}("${path}", (c) => {`,
        m === "DELETE"
          ? "  return c.body(null, 204);"
          : `  return c.json({ ok: true, method: "${m}" }${m === "POST" ? ", 201" : ""});`,
        "});",
        "",
      ]),
      `export default ${name};`,
    ]),
);

const DRIZZLE_COLUMN = {
  text: (n: string) => `text("${n}")`,
  integer: (n: string) => `integer("${n}")`,
  boolean: (n: string) => `boolean("${n}")`,
  timestamp: (n: string) => `timestamp("${n}", { withTimezone: true })`,
  uuid: (n: string) => `uuid("${n}")`,
} as const;

const drizzleTable = defineTemplate(
  "Drizzle `pgTable` with the repo conventions: `id` identity column always generated, `withTimezone: true` on every timestamp, and inferred insert/select types.",
  z
    .object({
      name: z
        .string()
        .regex(/^[a-z][a-z0-9_]*$/, "snake_case table name")
        .max(63),
      columns: z
        .array(
          z
            .object({
              name: z
                .string()
                .regex(/^[a-z][a-z0-9_]*$/, "snake_case column name")
                .max(63),
              type: z.enum(["text", "integer", "boolean", "timestamp", "uuid"]),
              primaryKey: z.boolean().default(false),
              notNull: z.boolean().default(false),
            })
            .strict(),
        )
        .min(1)
        .max(100),
    })
    .strict(),
  ({ name, columns }) => {
    const kinds = [...new Set(columns.map((c) => c.type))].sort();
    const toCamel = (s: string) => s.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
    const camel = toCamel(name);
    const Type = `${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
    const hasExplicitPk = columns.some((c) => c.primaryKey);
    return lines([
      `import { ${["pgTable", ...kinds].sort().join(", ")} } from "drizzle-orm/pg-core";`,
      "",
      `// ${name} — generated by @codai/axiom-emitters-web (web@2.0.0).`,
      "",
      `export const ${camel} = pgTable("${name}", {`,
      ...(hasExplicitPk ? [] : ['  id: integer("id").generatedAlwaysAsIdentity().primaryKey(),']),
      ...columns.map((c) => {
        const suffix = [
          c.primaryKey ? ".primaryKey()" : "",
          c.notNull && !c.primaryKey ? ".notNull()" : "",
        ].join("");
        return `  ${toCamel(c.name)}: ${DRIZZLE_COLUMN[c.type](c.name)}${suffix},`;
      }),
      "});",
      "",
      `export type ${Type} = typeof ${camel}.$inferSelect;`,
      `export type New${Type} = typeof ${camel}.$inferInsert;`,
    ]);
  },
);

const biomeConfig = defineTemplate(
  "Biome 2.5 config matching this repo's own style (2-space, width 100, double quotes, LF, `noExplicitAny` / `noConsole` / `noNonNullAssertion` as errors).",
  z.object({}).strict(),
  () =>
    lines([
      "{",
      '  "$schema": "https://biomejs.dev/schemas/2.5.14/schema.json",',
      '  "vcs": { "enabled": true, "clientKind": "git", "useIgnoreFile": true },',
      '  "files": { "includes": ["**", "!**/dist", "!**/.next"] },',
      '  "formatter": {',
      '    "enabled": true,',
      '    "indentStyle": "space",',
      '    "indentWidth": 2,',
      '    "lineWidth": 100,',
      '    "lineEnding": "lf"',
      "  },",
      '  "javascript": {',
      '    "formatter": { "quoteStyle": "double", "semicolons": "always", "trailingCommas": "all" }',
      "  },",
      '  "linter": {',
      '    "enabled": true,',
      '    "rules": {',
      '      "preset": "recommended",',
      '      "style": {',
      '        "noNonNullAssertion": "error",',
      '        "useImportType": "error",',
      '        "useNodejsImportProtocol": "error"',
      "      },",
      '      "suspicious": {',
      '        "noExplicitAny": "error",',
      '        "noConsole": { "level": "error", "options": { "allow": ["error", "warn"] } }',
      "      },",
      '      "correctness": { "noUnusedImports": "error", "noUnusedVariables": "error" }',
      "    }",
      "  }",
      "}",
    ]),
);

const tailwindGlobals = defineTemplate(
  'Tailwind v4 CSS-first entry (`@import "tailwindcss"` + an empty `@theme` block and light/dark tokens). No `tailwind.config.js`.',
  z.object({}).strict(),
  () =>
    lines([
      '@import "tailwindcss";',
      "",
      "@theme {",
      "  --color-background: oklch(1 0 0);",
      "  --color-foreground: oklch(0.145 0 0);",
      "  --radius: 0.625rem;",
      "}",
      "",
      "@layer base {",
      "  :root {",
      "    color-scheme: light dark;",
      "  }",
      "",
      "  body {",
      "    background-color: var(--color-background);",
      "    color: var(--color-foreground);",
      "  }",
      "}",
    ]),
);

const readmeSection = defineTemplate(
  "A single `## <title>` markdown section with the given body — the smallest useful template, meant for composing docs from a plan.",
  z.object({ title: z.string().min(1).max(120), body: z.string().max(8000) }).strict(),
  ({ title, body }) => lines([`## ${title}`, "", body.replace(/\r\n/g, "\n").trimEnd()]),
);

export const TEMPLATES: Record<string, TemplateDef> = {
  "biome.config": biomeConfig,
  "drizzle.table": drizzleTable,
  "hono.route": honoRoute,
  "next.route-handler": routeHandler,
  "next.server-action": serverAction,
  "readme.section": readmeSection,
  "tailwind.globals": tailwindGlobals,
};
