
    import type { Emitter } from "@axiom/engine/dist/emitter.js";
    const emitter: Emitter = {
      subtype: "batch-job",
      async generate(ctx) {

ctx.write("README.md", "# Batch Job\nGenerated by AXIOM (batch-job emitter).");
ctx.write("src/job.ts", `console.log('Batch job placeholder running at', new Date().toISOString());`);
ctx.write("package.json", JSON.stringify({
  name: "axiom-job",
  private: true,
  type: "module",
  scripts: { run: "node src/job.ts" }
}, null, 2));

      }
    };
    export default emitter;
