
import type { Emitter } from "@axiom/engine/dist/emitter.js";

const emitter: Emitter = {
  subtype: "docker-image",
  async generate(ctx) {
    ctx.write("Dockerfile", `FROM node:20-alpine
WORKDIR /app
COPY . .
RUN npm ci || true
CMD ["node","index.js"]
`);
    ctx.write(".dockerignore", `node_modules
npm-debug.log
`);
    ctx.write("index.js", "console.log('AXIOM docker image placeholder');\n");
    ctx.write("README.md", "# Docker Image\nGenerated by AXIOM (docker emitter).\n");
  }
};
export default emitter;
