import type { PlanInput } from "@codai/axiom-schema";
import fc from "fast-check";

type PlanArtifactInput = PlanInput["artifacts"][number];

const SEGMENT_RE: RegExp = /^[a-z0-9_-]{1,12}$/;
/** Windows device names that `RelPathSchema` rejects on every OS. */
const RESERVED_RE: RegExp = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i;
const EXTENSIONS: readonly string[] = ["", ".ts", ".tsx", ".md", ".json", ".txt", ".css"];

/** One path segment: `[a-z0-9_-]{1,12}` (never `.`/`..`, no reserved names, no trailing dot/space). */
export function segmentArb(): fc.Arbitrary<string> {
  return fc.stringMatching(SEGMENT_RE).filter((s) => !RESERVED_RE.test(s));
}

/** Valid `RelPath`: 1–4 segments joined by `/`, optional extension on the last one. */
export function relPathArb(): fc.Arbitrary<string> {
  return fc
    .tuple(fc.array(segmentArb(), { minLength: 1, maxLength: 4 }), fc.constantFrom(...EXTENSIONS))
    .map(([segments, ext]) => segments.join("/") + ext);
}

/** Text content that survives a JSON round-trip; no lone surrogates. */
export function textContentArb(maxLength = 512): fc.Arbitrary<string> {
  return fc.string({ minLength: 0, maxLength, unit: "grapheme" });
}

/** Arbitrary bytes, frequently containing NUL so base64 selection is exercised. */
export function binaryContentArb(maxLength = 512): fc.Arbitrary<Uint8Array> {
  return fc.uint8Array({ minLength: 0, maxLength });
}

/** Plan artifact with an inline source (utf8 or base64) or a delete. */
export function planArtifactArb(): fc.Arbitrary<PlanArtifactInput> {
  const mode = fc.constantFrom("0644", "0755") as fc.Arbitrary<"0644" | "0755">;
  const inlineText = fc
    .tuple(relPathArb(), mode, fc.constantFrom("create", "overwrite"), textContentArb())
    .map(
      ([path, m, op, content]): PlanArtifactInput => ({
        path,
        mode: m,
        op: op as "create" | "overwrite",
        source: { type: "inline", content },
      }),
    );
  const inlineBinary = fc.tuple(relPathArb(), mode, binaryContentArb()).map(
    ([path, m, bytes]): PlanArtifactInput => ({
      path,
      mode: m,
      source: {
        type: "inline",
        content: Buffer.from(bytes).toString("base64"),
        encoding: "base64",
      },
    }),
  );
  const del = relPathArb().map((path): PlanArtifactInput => ({ path, op: "delete" }));
  return fc.oneof(
    { weight: 5, arbitrary: inlineText },
    { weight: 3, arbitrary: inlineBinary },
    del,
  );
}

export interface PlanArbOptions {
  minArtifacts?: number;
  maxArtifacts?: number;
  /** Include `op: "delete"` artifacts (default true). */
  deletes?: boolean;
}

/** Valid `PlanInput` with unique artifact paths. */
export function planArb(opts: PlanArbOptions = {}): fc.Arbitrary<PlanInput> {
  const min = opts.minArtifacts ?? 2;
  const max = opts.maxArtifacts ?? 10;
  const art =
    opts.deletes === false ? planArtifactArb().filter((a) => a.op !== "delete") : planArtifactArb();
  const name = fc.stringMatching(/^[a-z0-9][a-z0-9-]{0,20}$/);
  return fc
    .tuple(name, fc.uniqueArray(art, { minLength: min, maxLength: max, selector: (a) => a.path }))
    .map(
      ([n, artifacts]): PlanInput => ({
        apiVersion: "axiom.dev/v2",
        kind: "Plan",
        name: n,
        intent: "generated by @codai/axiom-testkit",
        artifacts,
      }),
    );
}
