import type { Emitter } from "@axiom/engine/dist/emitter.js";

const emitter: Emitter = {
  subtype: "web-app-with-pii",
  async generate(ctx) {
    ctx.write("README.md", "# Web App with PII\nGenerated by AXIOM.");
    ctx.write("config.json", JSON.stringify({
      apiKey: "secret_1234567890",
      adminEmail: "admin@example.com",
      supportPhone: "0712345678"
    }, null, 2));
  }
};
export default emitter;
